apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: postgres-sql-instance-configuration-package
  annotations:
    provider: gcp
spec:
  crossplane:
    version: ">=v1.0.0-0"
  dependsOn:
    - provider: crossplane/provider-gcp
      version: ">=v0.13.0"